baseURL = "https://SiddAjriY2Jaccount.github.io/"
languageCode = "en-us"
title = "Siddhanth J Ajri"
theme = "personal-web"
copyright="© Siddhanth J Ajri"
googleAnalytics = ""
enableEmoji=true
enableRobotsTXT=true
pygmentsUseClasses=true
pygmentsCodeFences=true

[params.intro]
  main = "Hello, I'm Siddhanth :wave:"
  sub = "Welcome to my personal website/blog"

[taxonomies]
  design = "designs"
  tech = "techs"

[blackfriday]
  hrefTargetBlank = true

[params]
  breadcrumb = true
  accentColor = "#FD3519"
  mainSections = ['portfolio'] # values: ['post', 'portfolio'] only accept one section, to be displayed bellow 404

[params.notFound]
  gopher = "/images/gopher.png" # checkout https://gopherize.me/
  h1 = 'Bummer!'
  p = "It seems that this page doesn't exist."

[params.sections]
  # Define how your sections will be called
  # when automatically pulled. For instance in the 404 page
  post = "article"
  portfolio = "project"

[params.sidebar]
  backgroundImage = '/images/sidebar1.jpeg' # header background image - default "/images/default_sidebar.jpg" - Photo by Tim Marshall on Unsplash
  gradientOverlay = '' # default: rgba(0,0,0,0.4),rgba(0,0,0,0.4)
  logo = "/images/SJA.jpg" # - default "/images/edna-west.jpg"
[params.assets]
  favicon = "/images/fav.ico"
  customCSS = ""

[params.social]
  github = "https://github.com/SiddAjriY2Jaccount"
 # twitter = "https://twitter.com/"
  linkedin = "https://www.linkedin.com/in/siddhanth1997ajri"
 # medium = "https://medium.com/"
  #codepen = "https://codepen.io/"
  facebook = "https://www.facebook.com/siddhanth.jajari"
  #youtube = "https://www.youtube.com/"
  #instagram = "https://www.instagram.com/"
  #gitlab = "https://gitlab.com/"
  #keybase = "https://keybase.io/"

[params.contact]
  email = "contactsiddajri@gmail.com"
  text= "Get in touch!" # text of the contact link in the sidebar. If email params.contact.email is defined


[menu]

[[menu.main]]
  identifier = "about"
  name = "About"
  title = "About section"
  url = "/about/"
  weight = -120

[[menu.main]]
  identifier = "portfolio"
  name = "Portfolio"
  title = "Portfolio"
  url = "/portfolio/"
  weight = -110

[[menu.main]]
  identifier = "blog"
  name = "Post"
  title = "Blog section"
  url = "/post/"
  weight = -100

[sitemap]
  changefreq = "monthly"
  filename = "sitemap.xml"
  priority = 0.5

[privacy]
  [privacy.googleAnalytics]
    anonymizeIP = true
    disable = true
    respectDoNotTrack = true
    useSessionStorage = false
  [privacy.twitter]
    disable = false
    enableDNT = true
    simple = false
